LocalLibrary/LocalLibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

LocalLibrary/catalog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name = 'index'),
    path('books/', views.BookListView.as_view(), name = 'books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name = 'book-detail'),
    path('authors/', views.AuthorListView.as_view(), name = 'authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name = 'author-detail'),
    path('mybooks/', views.LoanedBookByUserListView.as_view(), name = 'mybooks'),
    path('allborrowed/', views.AllLoanedBookByUserListView.as_view(), name = 'all-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name="renew-book-librarian"),
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
    path('book/create/', views.BookCreate.as_view(), name='book_create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book_update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book_delete'),
]

LocalLibrary/catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length = 200, help_text = 'Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name} ({self.first_name})'


class Language(models.Model):
    name = models.CharField(max_length=200, help_text="Enter the book's natural language(e.g. English, French, Japanese, Arabic, etc.)")

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text ='Enter a brief description of athe book')
    isbn = models.CharField('ISBN', max_length=13, help_text ='13 Character <a href = "https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text ='Select a genre for this book')
    language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['title', 'author']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text ='Unique ID for this particular book across whole library')
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrowed = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')
    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return f'{self.id} ({self.book.title})'
    
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

LocalLibrary/catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import *
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from .form import RenewBookForm
from django.contrib.auth.decorators import permission_required
import datetime
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy


# Create your views here.
def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()
    num_genre = Genre.objects.count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    context = {
        'num_books' : num_books,
        'num_instances' : num_instances,
        'num_instances_available' : num_instances_available,
        'num_authors' : num_authors,
        'num_genre' : num_genre,
        'num_visits' : num_visits,
    }
    return render(request, 'catalog/index.html', context)


class BookListView(generic.ListView):
    model = Book
    paginate_by = 5

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author

class AuthorDetailView(generic.DetailView):
    model = Author

class LoanedBookByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 5

    def get_queryset(self):
        return BookInstance.objects.filter(borrowed=self.request.user).filter(status__exact='o').order_by('due_back')


class AllLoanedBookByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/all_borrowed_user.html'
    paginate_by = 5

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')

#@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    if request.method == 'POST':
        form = RenewBookForm(request.POST)

        if form.is_valid():
            book_instance.due_back = form.cleaned_data['renewal_data']
            book_instance.save()
            return HttpResponseRedirect(reverse('all-borrowed'))

    else:
        proposed_renewal_data = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_data})

    context = {
        'form' : form,
        'book_instance' : book_instance,
    }
    return render(request, 'catalog/renew_book_librarian.html', context)


class AuthorCreate(CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    initial = {'date_of_death': '11/06/2020'}

class AuthorUpdate(UpdateView):
    model = Author
    fields = '__all__' # Not recommended (potential security issue if more fields added)
    
class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')


class BookCreate(CreateView):
    model = Book
    fields = ['title', 'author', 'summary', 'isbn', 'genre', 'language']
    initial = {'date_of_death': '11/06/2020'}

class BookUpdate(UpdateView):
    model = Book
    fields = '__all__' # Not recommended (potential security issue if more fields added)
    
class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('authors')

LocalLibrary/catalog/templates/catalog/all_borrowed_user.html
{% extends 'catalog/base.html' %}

{% block content %}
    <h1>All Borrowed books</h1>
    {% if bookinstance_list %}
    <ul>
        {% for bookinst in bookinstance_list %}
            <li class="{% if bookinst.overdue %}text-danger{% endif %}">
                <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>{% endif %}
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There is no books brrowed!</p>
    {% endif %}
{% endblock %}

LocalLibrary/catalog/templates/catalog/author_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

LocalLibrary/catalog/templates/catalog/author_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
    <h1>Name: {{ author.first_name }} {{ author.last_name }}</h1>
    <p><strong>Date Of Birth: </strong>{{ author.date_of_birth }}</p>
    <p><strong>Date Of Death: </strong>{{ author.date_of_Death }}</p>
{% endblock %}

LocalLibrary/catalog/templates/catalog/author_form.html
{% extends 'catalog/base.html' %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

LocalLibrary/catalog/templates/catalog/author_list.html
{% extends 'catalog/base.html' %}

{% block content %}
    <h1>Author List</h1>
    {% if author_list %}
        <ul>
            {% for author in author_list %}
                <li>
                    <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no Authors</p>
    {% endif %}
    <a href="{% url 'author_create' %}"><strong>Add Author</strong></a>
{% endblock %}

LocalLibrary/catalog/templates/catalog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
        <title>Local Library</title>
    {% endblock %}
    <meta charset="utf-8">
   <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                    <ul class="sidebar-nav">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="{% url 'books' %}">All books</a></li>
                        <li><a href="{% url 'authors' %}">All authors</a></li>
                        {% if user.is_authenticated %}
                            <li>User: {{ user.get_username }}</li>
                            <li><a href="{% url 'mybooks' %}">My books</a></li>
                            <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
                        {% endif %}
                        <br>
                        <br>
                        <li><a href="{% url 'all-borrowed' %}">All borrowed</a></li>
                    </ul>
                {% endblock %}
            </div>
            <div class="col-sm-10">
                    {% block content %}
                    {% endblock %}
                    {% block pagination %}
                        {% if is_paginated %}
                            <div class="pagination">
                                <span class="page-links">
                                    {% if page_obj.has_previous %}
                                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                                    {% endif %}
                                    <span class="page-current">
                                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                    </span>
                                    {% if page_obj.has_next %}
                                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                                    {% endif %}
                                </span>
                            </div>
                        {% endif %}
                    {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

LocalLibrary/catalog/templates/catalog/book_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

LocalLibrary/catalog/templates/catalog/book_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
    <h1>Title: {{ book.title }}</h1>


    <p><strong>Author:</strong><a href="{% url 'author-detail' book.author.pk %}"> {{ book.author }}</a></p>
    <p><strong>summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Genre:</strong> {{ book.genre }}</p>
    <p><strong>Language:</strong> {{ book.language }}</p>

    <div style="margin-left: 20px; margin-top: 20px;">
        <h4>Copies</h4>
        {% for copy in book.bookinstance_set.all %}
            <hr>
            <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-denger{% else %}text-warning{% endif %}">
                {{ copy.get_status_display }}
            </p>
            {% if copy.status != 'a' %}
                <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
            {% endif %}
            <p><strong>Imprint: </strong> {{ copy.imprint }}</p>
            <p class="text-muted"><strong>ID:</strong> {{ copy.id }}</p>
        {% endfor %}
    </div>
{% endblock %}

LocalLibrary/catalog/templates/catalog/book_form.html
{% extends 'catalog/base.html' %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

LocalLibrary/catalog/templates/catalog/book_list.html
{% extends 'catalog/base.html' %}

{% block content %}
    <h1>Book List</h1>
    {% if book_list %}
        <ul>
            {% for book in book_list %}
                <li>
                    <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }})
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are no books in the Library</p>
    {% endif %}
    <a href="{% url 'book_create' %}"><strong>Add Book</strong></a>
{% endblock %}

LocalLibrary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends 'catalog/base.html' %}

{% block content %}
    <h1>Borrowed books</h1>
    {% if bookinstance_list %}
    <ul>
        {% for bookinst in bookinstance_list %}
            <li class="{% if bookinst.overdue %}text-danger{% endif %}">
                <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a>
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There is no books brrowed!</p>
    {% endif %}
{% endblock %}

LocalLibrary/catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}

{% block content %}
    <h1>LIBRARY Home</h1>
    <p>Welcome to LocalLibrary</p>
    <h2>Dynamic content</h2>
    <p>the library has the following record counts:</p>
    <ul>
        <li><strong>Books:</strong> {{ num_books }}</li>
        <li><strong>Copies:</strong> {{ num_instances }}</li>
        <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
        <li><strong>Authors:</strong> {{ num_authors }}</li>
        <li><strong>Genres:</strong> {{ num_genre }}</li>
    </ul>
    <p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>
{% endblock %}

LocalLibrary/catalog/templates/catalog/renew_book_librarian.html
{% extends 'catalog/base.html' %}

{% block content %}
    <h1>Renew: {{ book_instance.book.title }} </h1>
    <p>Borrower: {{ book_instance.borrower }} </p>
    <p {% if book_instance.is_overdue %} class="text-danger" {% endif %} > Due date: {{ book_instance.due_back }} </p>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}